name: Code Quality and Testing

on: [push]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python 3.12
      run: uv python install 3.12
    
    - name: Install dependencies
      run: |
        uv sync --dev
        uv add --dev ruff mypy
    
    - name: Ruff format check
      run: uv run ruff format --check .
    
    - name: Ruff lint check  
      run: uv run ruff check .
    
    - name: Type checking with MyPy
      run: uv run mypy .
      continue-on-error: true
